CREATE SCHEMA IF NOT EXISTS BOOKSHELF;

CREATE TABLE IF NOT EXISTS BOOKSHELF.USER
(
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    IS_LOGGED BOOLEAN NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BOOKSHELF.SEQ_USER MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BOOKSHELF.BOOK
(
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL,
    AUTHOR VARCHAR2(100),
    CREATED_DATE DATE NOT NULL,
    USER_ID NUMBER(11) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BOOKSHELF.SEQ_BOOK MINVALUE 1 START WITH 1 INCREMENT BY 1;